/* Generated by tools/../genweaponart.py from the original's weapon clip.
   Every weapon has its own frame in that clip, so every weapon has its
   own silhouette bounds and its own fills -- which is why a single shared
   "broad blade" for eleven of them was wrong.  The box and the three
   dominant fills below are the original's; the silhouette family is this
   project's reading of its proportions, and art.c draws every shape. */
/* The WeaponArt row itself is declared in game.h. */

static const WeaponArt WEAPON_ART[] = {
  /* index 0 is "no named weapon": a Look that never set weaponArt lands here
     and falls back to its silhouette family and its own tint. */
  { "None",            WEAP_NONE,      0,   0, {   0,  0,  0,255 }, {   0,  0,  0,255 }, {   0,  0,  0,255 }, 0 },
  { "Iron Knife",      WEAP_KNIFE,    47,  31, { 101,101,101,255 }, {  87, 87, 87,255 }, {  51, 51, 51,255 }, 0 },
  { "Energy Knife",    WEAP_KNIFE,    47,  31, {  51, 51, 51,255 }, {  87, 87, 87,255 }, {  51,153,204,255 }, 0 },
  { "Silver Knife",    WEAP_KNIFE,    50,  33, {  51, 51, 51,255 }, { 101,101,101,255 }, {  87, 87, 87,255 }, 0 },
  { "Spiked Axe",      WEAP_AXE,      47,  39, { 112,112,112,255 }, { 151,151,151,255 }, { 102,102,102,255 }, 0 },
  { "Heavy Blade",     WEAP_CLEAVER,  42,  37, {  51, 51, 51,255 }, {  96, 96, 96,255 }, { 106,106,106,255 }, 0 },
  { "Wooden Rod",      WEAP_STAFF,    44,  37, { 119,119,119,255 }, { 250,250,250,255 }, { 117,117,117,255 }, 0 },
  { "Golden Rod",      WEAP_STAFF,    47,  35, { 255,255,255,255 }, { 153,102,  0,255 }, { 255,204,  0,255 }, 0 },
  { "Katana",          WEAP_KATANA,   44,  36, { 151,102, 55,255 }, { 109, 74, 39,255 }, { 187,128, 68,255 }, 0 },
  { "Shield Breaker",  WEAP_CLEAVER,  40,  38, { 102,102,102,255 }, {  80, 80, 80,255 }, { 119,119,119,255 }, 0 },
  { "Blaze Edge",      WEAP_KATANA,   44,  32, { 102,102,102,255 }, { 119,119,119,255 }, { 250,250,250,255 }, 0 },
  { "Fusion Edge",     WEAP_ENERGY,   44,  38, { 102,102,102,255 }, { 236,252,253,255 }, { 119,119,119,255 }, 0 },
  { "Blood Razor",     WEAP_RAZOR,    44,  36, { 119,119,119,255 }, { 250,250,250,255 }, { 117,117,117,255 }, 0 },
  { "Shadow Katana",   WEAP_KATANA,   44,  36, { 187,128, 68,255 }, {  58, 58, 58,255 }, {  92, 92, 92,255 }, 0 },
  { "Shadow Spirit",   WEAP_BROAD,    45,  41, {  64, 64, 64,255 }, {  92, 92, 92,255 }, { 187,128, 68,255 }, 0 },
  { "Golden Blade",    WEAP_BROAD,    41,  42, {   0, 51,  0,255 }, {  64, 64, 64,255 }, { 102,102,102,255 }, 0 },
  { "Rust Blade",      WEAP_CLEAVER,  39,  43, { 102,102,102,255 }, {  74, 74, 74,255 }, { 189,187,172,255 }, 0 },
  { "Guard Blade",     WEAP_BROAD,    50,  44, { 102,102,102,255 }, {  82, 82, 82,255 }, { 119,119,119,255 }, 0 },
  { "Ion Bo",          WEAP_ENERGY,   49,  50, { 103,103,103,255 }, { 137,116, 90,255 }, {  60, 50, 40,255 }, 0 },
  { "Raider Sword",    WEAP_BROAD,    42,  38, { 151,102, 55,255 }, {  71, 71, 71,255 }, {   0,  0,  0,255 }, 0 },
  { "Double Razor",    WEAP_RAZOR,    45,  38, { 102,102,102,255 }, {  64, 64, 64,255 }, {   0, 51,  0,255 }, 0 },
  { "Wooden Staff",    WEAP_STAFF,    48,  32, { 255,255,255,255 }, {  48,197, 27,255 }, {  50,125, 13,255 }, 0 },
  { "Spike Sword",     WEAP_SPIKE,    42,  39, { 255,204,102,255 }, { 190,119,  1,255 }, { 190,119,  1,255 }, 0 },
  { "Demon Sword",     WEAP_SPIKE,    44,  44, { 116,245,116,255 }, {  52,165, 71,255 }, { 186,186,186,255 }, 1 },
  { "Long Sword",      WEAP_BROAD,    44,  45, { 102,102,102,255 }, { 222,126, 12,255 }, { 251,207, 79,255 }, 0 },
  { "Fallen Blade",    WEAP_BROAD,    50,  36, {  96, 63,107,255 }, { 183,151,193,255 }, { 194,168,204,255 }, 1 },
};
